### ISSUE TITLE
How to use 

### ISSUE THREAD

**Issue by aaronteamAAR** [Darkempire78/Duolingo-Word-List-Generator#1]
Please can you explain more on how I can use this

**Comment by Darkempire78** [comment]
1) Install Python
2) Install modules : `pip install -r requirements.txt`
3) Config the config file
```Js
{
    "username": "My Duolingo Username",
    "password": "My Duolingo Password",
    "learningLanguage": "The language that I am learning ex: fr",
    "yourLanguage": "My fluent language ex : en"
}
```
4) Rename the config file to `config.json`
5) Run the script with python
6) It will generate an html file
7) Open the html file and be happy

Tell me if you have any issue @aaronteamAAR

**Comment by aaronteamAAR** [comment]
Thanks
